server:
  port: 80
spring:
  application:
    name: PBlog
  datasource:
    druid:
      url: jdbc:mysql://39.106.97.88:3306/p-blog?userUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      password: root
      username: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    ehcache:
      config: classpath:ehcache.xml

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    cache-enabled: true
#  config-location: classpath:mybatis-config.xml
logging:
  level:
    com.ponking.pblog: debug

pblog:
  elasticsearch:
    host: 39.106.97.88
    port: 9200
    scheme: http
  web:
    domain: 121.36.90.108 #121.36.90.108 39.106.97.88

