spring:
  profiles:
    active: dev
  # thymeleaf模板配置
  thymeleaf:
    suffix: .html
    mode: HTML5
    encoding: utf-8
    cache: false
#    prefix: classpath:/templates/blog,/templates/admin
  # BANNER
  banner:
    location: classpath:banner.txt
    image:
      height: 50
      margin: 2
      invert: false
      width: 50
    charset: utf-8

jwt:
  # AES密码加密私钥(Base64加密)
  encryptAESKey: V2FuZzkyNjQ1NGRTQkFQSUpXVA==
  # JWT认证加密私钥(Base64加密)
  encryptJWTKey: U0JBUElKV1RkV2FuZzkyNjQ1NA==
  # AccessToken过期时间-5分钟-5*60(秒为单位)
  accessTokenExpireTime: 300
  # RefreshToken过期时间-30分钟-30*60(秒为单位)
  refreshTokenExpireTime: 1800
  # Shiro缓存过期时间-5分钟-5*60(秒为单位)(一般设置与AccessToken过期时间一致)
  shiroCacheExpireTime: 300




