server:
#  servlet:
#    context-path: /dev-api
  port: 8080

spring:
  application:
    name: PBlog
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/p-blog?userUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      password: root
      username: root
      driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml

pblog:
  author-name: PonKing
  author-title: 我就是我,颜色不一样的烟火
  author-location: 广东肇庆
  author-avatar: \images\avatar.jpg
