server:
#  servlet:
#    context-path: /dev-api
  port: 8080

spring:
  application:
    name: PBlog
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/p-blog?userUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      password: root
      username: root
      driver-class-name: com.mysql.cj.jdbc.Driver
#  cache:
#    ehcache:
#      config: classpath:ehcache.xml

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    cache-enabled: true
#  config-location: classpath:mybatis-config.xml
logging:
  level:
    com.ponking.pblog: debug

pblog:
  elasticsearch:
    host: 192.168.170.22
    port: 9200
    scheme: http
  web:
    domain:
