spring:
  profiles:
    active: dev
  # thymeleaf模板配置
  thymeleaf:
    suffix: .html
    mode: HTML5
    encoding: utf-8
    cache: false
#    prefix: classpath:/templates/blog,/templates/admin

jwt:
  expire-time: 12000000
  secret-key: 19980606



