spring:
  profiles:
    active: prod
  # thymeleaf模板配置
  thymeleaf:
    suffix: .html
    mode: HTML5
    encoding: utf-8
    cache: false
#    prefix: classpath:/templates/blog,/templates/admin
  # BANNER
  banner:
    location: classpath:banner.txt
    image:
      height: 50
      margin: 2
      invert: false
      width: 50
    charset: utf-8

jwt:
  expire-time: 12000000
  secret-key: 19980606




